######todo not finished
AWSTemplateFormatVersion: '2010-09-09'
Description: 'ELK'

Resources:
  # Creates a user pool for kibana
######todo not finished
AWSTemplateFormatVersion: '2010-09-09'
Description: 'ELK'

Resources:

#############
#
#  Cognito Part
#
#############

  ELKDomainRole:
    Type: "AWS::IAM::Role"
    Properties:
       AssumeRolePolicyDocument:
         Version: 2012-10-17
         Statement:
           - Effect: Allow
             Principal:
               Service: "es.amazonaws.com"
             Action: "sts:AssumeRole"
       Path: /service-role/
       ManagedPolicyArns:
         - arn:aws:iam::aws:policy/AmazonESCognitoAccess
       RoleName: !Sub 'elk_domain_role_${AWS::Region}'


  ElasticsearchDomain:
    Type: 'AWS::Elasticsearch::Domain'
    Properties:
      AccessPolicies:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            AWS: '*'
          Action:
          - 'es:ESHttp*'
          Resource: !Sub 'arn:aws:es:${AWS::Region}:${AWS::AccountId}:domain/elkdemo/*'
      DomainName: elkdemo
      #https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/what-is-amazon-elasticsearch-service.html#aes-choosing-version
      ElasticsearchVersion: 7.1
      EBSOptions:
         EBSEnabled: true
         Iops: 0
         VolumeSize: 100
         VolumeType: "gp2"
      ElasticsearchClusterConfig:
        DedicatedMasterCount: "3"
        DedicatedMasterEnabled: "true"
        DedicatedMasterType: "r5.large.elasticsearch"
        #You must choose an even number of data nodes for a two Availability Zone deployment 
        InstanceCount: "4"
        InstanceType: "r5.large.elasticsearch"
        ZoneAwarenessEnabled: "true"
      CognitoOptions:
          Enabled: "true"
          IdentityPoolId: !ImportValue  cognito-CognitoIdentityPoolId
          RoleArn: !GetAtt ELKDomainRole.Arn
          UserPoolId: !ImportValue cognito-CognitoUserPoolId
      #EncryptionAtRestOptions:  {Enabled: true, KmsKeyId: asdfasdf}
    UpdatePolicy:
      EnableVersionUpgrade: false

Outputs:
  StackName:
    Description: 'Stack name.'
    Value: !Sub '${AWS::StackName}'
